[project]
name = "bonjour"
version = "0.1.0"
description = "French phrase CLI"
dependencies = [
  "dotenv==0.9.9",
  "openai==1.79.0",
  "python-dotenv==1.1.0",
  "rich==14.0.0",
  "typer==0.15.4",
]
requires-python = ">=3.10"

[project.scripts]
bonjour = "bonjour.main:greet"
